Ml service
Viltsev/IST_Viltsev pull request #3
Opened 2024-03-19 18:17 UTC by Viltsev

2024-03-25 13:47 UTC, nrydanov requested changes
In general, everything is OK. There're some strange decisions (for example, passing red/blue/green as separate arguments), but it's small problems. The only problem I've found — image classification logic.

2024-03-28 18:10 UTC, MakDaffi requested changes

2024-03-28 18:10 UTC, MakDaffi commented on application/machine_learning/image_classifier.py
> +                         metrics=['accuracy'])
Do you really need parameters for train model on inference?

2024-03-28 18:10 UTC, MakDaffi commented on application/machine_learning/image_classifier.py
> +    model_save_path = os.path.join(os.path.dirname(__file__), "new_model_training.h5")
The path to the model must be in config.

2024-03-28 18:10 UTC, MakDaffi commented on application/machine_learning/new_model_training.h5
The model weights must be in the .gitignore file.

2024-03-28 18:10 UTC, MakDaffi commented on application/machine_learning/context.py
> +    background_image = "background.jpg"
Why is this parameter needed?

2024-03-28 18:10 UTC, MakDaffi commented on application/machine_learning/context.py
> +    source_image = "imagesWithoutBackground/693580eeae135ee71a39dbe8e3237bb1.png"
Why is this parameter needed?

2024-03-28 18:10 UTC, MakDaffi commented on application/machine_learning/requirements.txt
> +asyncio~=3.4.0
You have pyproject.toml in the root with the same dependencies. Question: why do you also need requirements.txt?

2024-04-02 18:12 UTC, Viltsev commented on application/machine_learning/requirements.txt
> +asyncio~=3.4.0
> You have pyproject.toml in the root with the same dependencies. Question: why do you also need requirements.txt?

Forgot to delete it, i've corrected it now.

2024-04-04 15:19 UTC, MakDaffi requested changes

2024-04-04 15:19 UTC, MakDaffi commented on application/machine_learning/MLController.py
> +    await find_images.main(ctx.source_image, ctx.images_without_background, ctx.similar_images)
Why doesn't endpoint accept anything? Do I understand correctly that you do not specify image, but take one pre-selected file and look for similar ones? If this is so, then it is incorrect.

2024-04-04 15:19 UTC, MakDaffi commented on application/machine_learning/context.py
> +    background_image = "background.jpg"
This parameter should be passed to the endpoint as a request (I mean, not the parameter itself, but the image), rather than passed to the system as configuration.

2024-04-04 15:19 UTC, MakDaffi commented on application/machine_learning/context.py
> +    source_image = "imagesWithoutBackground/693580eeae135ee71a39dbe8e3237bb1.png"
This parameter should be passed to the endpoint as a request (I mean, not the parameter itself, but the image), rather than passed to the system as configuration.

2024-04-04 15:23 UTC, Viltsev commented on application/machine_learning/context.py
> +    source_image = "imagesWithoutBackground/693580eeae135ee71a39dbe8e3237bb1.png"
> This parameter should be passed to the endpoint as a request (I mean, not the parameter itself, but the image), rather than passed to the system as configuration.

I need to send path of the folder and name of the image like request parameter?

2024-04-04 15:24 UTC, Viltsev commented on application/machine_learning/context.py
> +    source_image = "imagesWithoutBackground/693580eeae135ee71a39dbe8e3237bb1.png"
> This parameter should be passed to the endpoint as a request (I mean, not the parameter itself, but the image), rather than passed to the system as configuration.

Should I pass the folder path and name of the photo as a request parameter?

2024-04-04 15:25 UTC, Viltsev commented on application/machine_learning/MLController.py
> +    await find_images.main(ctx.source_image, ctx.images_without_background, ctx.similar_images)
> Why doesn't endpoint accept anything? Do I understand correctly that you do not specify image, but take one pre-selected file and look for similar ones? If this is so, then it is incorrect.

okay, i'm going to correct it.

2024-04-12 13:03 UTC, merged